# Generated by Django 4.2.5 on 2023-09-12 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='category_id',
            new_name='category',
        ),
    ]
