# Generated by Django 4.2.5 on 2023-09-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_category_id_expense_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='payment_method_id',
            new_name='payment_method',
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
