version: '3'

services:
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"