# Generated by Django 4.2.5 on 2023-10-26 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_expense_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentMethod',
            new_name='Payment',
        ),
    ]
