# Generated by Django 4.2.5 on 2023-10-26 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_paymentmethod_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='payment_method',
            new_name='payment',
        ),
    ]
